//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facility1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seller()
        {
            this.Order = new HashSet<Order>();
            this.Seller1 = new HashSet<Seller>();
        }
    
        public System.Guid iSeller { get; set; }
        public int SellerNumber { get; set; }
        public string SellerName { get; set; }
        public string SellerSurname { get; set; }
        public System.DateTime SellerCreatedAt { get; set; }
        public Nullable<decimal> SellerGoal { get; set; }
        public Nullable<decimal> SellerSales { get; set; }
        public Nullable<System.Guid> iSellerDirector { get; set; }
        public System.Guid iLocation { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seller> Seller1 { get; set; }
        public virtual Seller Seller2 { get; set; }
    }
}
